services:
  - type: web
    name: tescgsm-admin
    runtime: node
    plan: free
    branch: production
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PORT
        value: "3306"
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      - key: MYSQL_ROOT_USER
        sync: false
      - key: MYSQL_ROOT_PASSWORD
        sync: false
      - key: CORS_ORIGINS
        value: https://tescgsm.es,https://www.tescgsm.es,https://admin-tescgsm.es
